services:
  - type: web
    name: this-or-that-with-her
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: NODE_VERSION
        value: 18
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
